### ISSUE TITLE
升级到2.2.2后showPopupWindow(View v)位置问题

### ISSUE THREAD

**Issue by x200516** [razerdp/BasePopup#279]
- 系统版本：5.01
 - 库版本：2.2.2
 - 问题描述/重现步骤：最简单的调用,点击"待定"按钮,2.2.1 调用 showPopupWindow(View v)位置还正常,升到2.2.2后就下移了
 - 问题代码/截图：http://chuantu.xyz/t6/728/1586582619x1700338641.png
 - 报错信息：

---

**Comment by razerdp** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        ya，针对这个问题，我在2.2.2.2修复了，请升级到新版
        另外尽量在issue中提出问题哦~邮件太多了，容易忽略
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                razerdp123
                            
                    
                        
                            
                                    razerdp123@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年4月11日 13:25，x200516<notifications@github.com> 写道： 






系统版本：5.01

库版本：2.2.2

问题描述/重现步骤：最简单的调用,点击"待定"按钮,2.2.1 调用 showPopupWindow(View v)位置还正常,升到2.2.2后就下移了

问题代码/截图：http://chuantu.xyz/t6/728/1586582619x1700338641.png

报错信息：







—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
